# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Create app user and group, then create directory and set permissions
RUN groupadd -g 1000 appgroup && \
    useradd -r -u 1001 -g appgroup appuser && \
    mkdir media && \
    chown 1001:0 media && \
    chmod 755 media

# Copy the current directory contents into the container at /app
COPY --chown=1001:0 . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000

# Run the container as non-root user
USER 1001

# Run Django application
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "image_predictor.wsgi:application"]
